# Generated by Django 5.0.6 on 2024-08-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.BigIntegerField(unique=True)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.BigIntegerField()),
                ('logo_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'validation',
            },
        ),
        migrations.CreateModel(
            name='TeamCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.categories')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.teams')),
            ],
            options={
                'db_table': 'team_categories',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('team_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.teamcategories')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Crosses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.teams')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crosses_visitor_team_set', to='faf_api.teams')),
            ],
            options={
                'db_table': 'crosses',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.crosses')),
                ('local_team_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.teamcategories')),
                ('visitor_team_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_visitor_team_category_set', to='faf_api.teamcategories')),
                ('local_validation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.validation')),
                ('visitor_validation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_visitor_validation_set', to='faf_api.validation')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='ValidationPlayers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.players')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.validation')),
            ],
            options={
                'db_table': 'validation_players',
            },
        ),
    ]
