# Generated by Django 5.0.6 on 2024-10-17 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faf_api.players')),
            ],
            options={
                'db_table': 'player_images',
            },
        ),
    ]
