# Generated by Django 5.0.6 on 2024-08-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
