# Generated by Django 5.0.6 on 2024-09-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf_api', '0002_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
