# Generated by Django 5.0.6 on 2024-10-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf_api', '0002_playerimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerimages',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
