# Generated by Django 5.0.6 on 2024-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faf_api', '0003_alter_players_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
